### PR TITLE
Reenable perl debugging ("perl -de 1" possible again)

### LINKED ISSUE #292: Reenable perl debugging
"perl -de 1" is not possible any more.  This is basic perl and should just working, because the two files lib/perl5/5.8.8/dumpvar.pl and lib/perl5/5.8.8/perl5db.pl are in any basic perl setup and cannot be loaded afterwards via CPAN, ...

### PR DESCRIPTION
**Pull request by Dirk1966**
Undeleted the files lib/perl5/5.8.8/dumpvar.pl and lib/perl5/5.8.8/perl5db.pl
to reenable perl debugging.

git-commands:
git checkout c3b46a47f2086481c33c989fe418d7c01d553b72^ -- lib/perl5/5.8.8/dumpvar.pl
git checkout c3b46a47f2086481c33c989fe418d7c01d553b72^ -- lib/perl5/5.8.8/perl5db.pl

Fixes #292

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks. Since you've also created issue #292 about this, could you please modify your commit message so that it will [auto-close the issue](https://help.github.com/articles/closing-issues-via-commit-messages/) when merging the PR?

**Comment by Dirk1966** [comment]
Added
Fixes #292
to comment, so that issue #292 will automatically will be closed after push.

**Comment by Dirk1966** [comment]
Sorry, still unfamiliar with the workflows.  Added
"Fixes #292"
to the git commit message, so that issue #292 will be closed automatically, if the changes are pulled.

**Comment by sschuberth** [comment]
Thanks, but the sign-off in the commit message is still missing (`git commit --amend -s`).

**Comment by Dirk1966** [comment]
I changed the comment on the commit message again and hope that now all is O.K.

**Comment by Farhaaad-saaami** [comment]
nana_11.nana11nana-11@hotmail.com

**Pull request merged**
