### PR TITLE
Added expat and xz release scripts, and also repaired the large majority...

### PR DESCRIPTION
**Pull request by ColonelJ**
... of other builds in /src.  Also a new script has been created to cleanup the output of these builds which is no longer required once installed.  N.B. 'file' should be built and rebuilt first as the -L change is required for proper functioning of libtool (which is also used in the compilation of file).

Essentially I had wiped everything in the mingw directory, installed the latest TDM GCC toolchain and built all other necessary bits up from scratch using these src releases.  'expat' was missing and I thought xz would be useful since it allows opening those lzma files published by MINGW (and there's quite a lot of other archiver builds in there already so strange to leave this one).

Hope you can accept these changes and it is useful to some people.  Of course if this is accepted someone should run the /src/xz/release.sh and roll that into the branch as well.

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks for this! I realize this must have been a lot of work, but unfortunately we're going to deprecate this way of building packages soon in favor of https://github.com/git-for-windows/sdk-packages.

But now that we have it, we should take it. A few quick notes from my side:

- I wish it was one commit per package that you add or modify.
- Each commit's subject should not exceed 75 chars in length, and the commit message body text should also be hard-wrapped at 75 chars.
- I'm a bit concerned about you using the latest TDM GCC tool chain. Does it mean it will not out of the box with the tool chain we currently use?

**Comment by ColonelJ** [comment]
Hi, I split it down into lots of separate commits for you each with a message <75 chars.

Forgot to mention this before but on top of building xz, the file.exe contained in the repo absolutely needs to be rebuilt since it does not accept the -L option and this can cause problems with detection of libraries by libtool scripts (which always seems to use this option even though it's on by default).

There is quite a lot of variety behind the modifications I made here.  Some of them may be just due to the environment, differences in includes, gcc options available, different git settings etc.  However some of them are real problems that ought to happen regardless of toolchain, and just problems with broken URLs are enough to make the out of the box tools fail on these!  Also the order things are built initially probably matters quite a lot since ./configure will pick up the results of installing other builds, so it may be a case of it can work but it doesn't always.

Anyway, I'm not aware of anything I changed which might make things less likely to build than they were before.

After taking these commits someone with a trusted build machine needs to rebuild file.exe (at least) and could helpfully install xz binaries as well.

**Comment by sschuberth** [comment]
Sorry for not coming back to this earlier, and thanks again for your work. There still are a bunch of formal issues with your commits like

* Missing sign-offs
* Use of trailing dot in commit message title
* Use of past tense in commit message title (prefer "Patch msmtp package" over "Patched rebase package")

Also, most of your commits just say in prose what is obvious from the diff, but there is no rationale. For example, *why* does it make sense to "Patch msmtp package to include socket headers before OpenSSL headers" (similar for other commits)? The explanation for that should go into the commit message body.

Anyway, I don't want to waste your time. We're currently working on an [MSYS2-based Git for Windows](https://github.com/git-for-windows) which comes with a completely different packaging system. That said, even if you were reworking your PR so that I could merge it, we probably won't build and bundle the binaries anymore as we consider msysgit to be more or less deprecated.

**Comment by ColonelJ** [comment]
I do recognise that a proper native Git within MSYS2 might be the best way forward and if that works properly would make msysgit (and this related work) mostly redundant.  So if it were available right now that would be really great...  Unfortunately it's not, and messing around with a system with some history that I know to work already (without the sluggishness of Cygwin) doesn't seem such a bad idea.

I mainly put these changes down in case someone else could see the value in them and wanted to redo the commits in the proper and formal way, including fresh binaries for the applications concerned.  I never intended to do this myself, but if anyone wants to do it they should go ahead.  I might have other changes to support mingw64 32-bit toolchain which aren't present yet (and Git itself does need other patches as done for MSYS2).

Thanks for the tips on commit messages though, I think that's useful; not sure how standard these rules/guidelines are?  Rationale for commits in the commit message seems a great idea, since the problems fixed might not be obvious.  (FWIW I think the commit you picked out was related to the OpenSSL including winsock.h rather thann winsock2.h, thus causing a conflict.  But, I'm not going to look through all the others!)

Anyway, thanks for your comment, and God's speed for a proper Git in MSYS2 - hopefully it can work as well as msysgit has done for all these years.

**Comment by dscho** [comment]
@ColonelJ Yeah, I think your addition is a good one, so if you could adjust the commit messages accordingly, I would merge and build (but as @sschuberth indicated, we now really focus on an MSys2-based Git for Windows, so I won't make a new release, your work would "only" be available via the net installer, hope that's okay with you?).

> Thanks for the tips on commit messages though, I think that's useful; not sure how standard these rules/guidelines are?

The upstream Git project has [these guidelines](https://github.com/git/git/blob/d67f9d5e8fd2c165304153a87fd96054d2b74981/Documentation/SubmittingPatches#L90-L117) and we try to follow them, too.

> Anyway, thanks for your comment, and God's speed for a proper Git in MSYS2

See [the milestone](https://github.com/git-for-windows/git/milestones/First%20release%20of%20Git%20for%20Windows%20generated%20using%20the%20new%20SDK)... ;-)

> hopefully it can work as well as msysgit has done for all these years.

Considering that the same people drive this project forward, I'd expect that to be the case...

**Comment by ColonelJ** [comment]
If you do want to merge it, then I think I'd be happy to put in a little more effort to check the changes are all up to date and that the commit messages explain the changes better.  However I can't add a sign off to my own commits unless you're happy with it going in as an alias (which would still be breaking the guidelines).

On your milestone, It doesn't seem clear yet how this new Git would be installed from MSYS2 or that this milestone is relevant to MSYS2 specifically (the SDK is based on original MSYS?)...

As for MSYS2, I think I was just worried that something about the MSYS2 environment or when building the libraries under a different toolchain might change the behaviour.  To my best knowledge/experience, these are indeed real issues (which aren't automatically solved by having the right developers!)

**Comment by dscho** [comment]
> If you do want to merge it, then I think I'd be happy to put in a little more effort to check the changes are all up to date and that the commit messages explain the changes better.

Well, you put in a lot of effort, and I think it would be a shame if it was for naught.

> I can't add a sign off to my own commits unless you're happy with it going in as an alias

Can't you just sign off with your real name and a fake email address like `<ColonelJ@users.github.com>`?

> It doesn't seem clear yet how this new Git would be installed from MSYS2

The plan is to [use the same mechanism](https://github.com/git-for-windows/git/issues/13) as with the current Git for Windows. Ideally, users will not even notice that the SDK is based on a different MSys, except maybe that more things work.

> I was just worried that something [...] might change the behaviour.

Our benchmark is Git's own test suite. There will be no release that does not pass it.

**Comment by dscho** [comment]
@ColonelJ thank you for your hard work! As I explained previously, I think it is now even easier to contribute with the new Git SDK, and even better: it already has the packages you desired. Also: Git for Windows 2.x was released, and since that supersedes 1.x I do not think that we have any need for any development in msysGit anymore. I am sure you agree...

**Pull request closed without merging**
