### PR TITLE
Make ln create Windows symlinks

### PR DESCRIPTION
**Pull request by ghost**
This was discussed a while back here
- [groups.google.com/group/msysgit/browse_thread/thread/c8e70e2507d36ede](http://groups.google.com/group/msysgit/browse_thread/thread/c8e70e2507d36ede)

Currently when I build git on Windows, all `ln -s` does is make a copy of the file.

This script is one way to actually make the symlinks in `libexec/git-core`.

You can put it right alongside `ln.exe` and it will be used first.
- [stackoverflow.com/questions/9248147](http://stackoverflow.com/questions/9248147)

### CODE REVIEW

**Comment by ghost** [comment]
@dscho I know this repo is old, but I dont know where to put this comment. I
found a better solution for this old problem:

``` sh
export CYGWIN=winsymlinks:native
ln -s alfa.exe bravo.exe
```

http://stackoverflow.com/q/3648819/make-symbolic-link-with-cygwin#18660841

Let me know if I should post this somewhere else.

**Comment by dscho** [comment]
@svnpenn please note that it is perfectly fine to add valuable information even to unmaintained repositories' bug trackers. As long as you know that no help can be expected.

BTW your StackOverflow link currently just leads me to this page:

stackoverflowoffline

To avoid such inconveniences (and the same applies for reading GitHub notifications as mail, during a lengthy trip without internet access), I always recommend to accompany hyperlinks with an appropriate summary (which your two-liner solution probably is). Such summaries are simple, easy and a possible life saver.

**Comment by ghost** [comment]
@dscho should I just repost this to git/git? Or is there a new msysgit/msysgit? You didnt really address my concern: you said its ok to post here (although useless), but you didnt say WHERE would be better to post.

**Comment by dscho** [comment]
No need to repost. And your post was not useless, as it was answering (and Google will find it), not asking.

**Comment by dscho** [comment]
BTW I could imagine that https://github.com/git-for-windows/git/wiki would be an excellent place to post this information.

**Comment by ghost** [comment]
@dscho I dont think you are getting me. My concern is that the original issue
listed above has not been resolved. That building Git for Windows create copies
in `libexec/git-core` rather than symlinks.

If that is the case my recent comment could be a solution to that. So I dont
just want these comments here for Google users, I want to fix the problem.

**Comment by dscho** [comment]
We never put symlinks, but instead _hardlinks_ into `libexec/git-core/`.

Besides, your solution works only for administrators by default. See https://github.com/git-for-windows/git/wiki/Symbolic-links for details.

**Pull request closed without merging**
