### PR TITLE
fix DLL relocation problem with recompiled SVN libs

### PR DESCRIPTION
**Pull request by kblees**
Damn, I'm three hours late for today's maintainance release (big thanks Thomas!).

Luckily, the installer comes with rebase, so people using SVN can simply rebase the two affected libraries themselves.

---8<---
Recompiled libsvn_repos and libneon have the same base address, causing
problems in MSYS fork emulation. Rebase to free regions via:

  rebase -b 0x64000000 bin/libsvn_repos-1-0.dll
  rebase -b 0x64200000 bin/libneon-25.dll

Signed-off-by: Karsten Blees blees@dcon.de

### CODE REVIEW

**Comment by albfan** [comment]
I suffer same problem with `libsvn_delta-1-0.dll`

Solve it issuing:
    > cd "C:\Program Files (x86)\Git\bin"
    > rebase -b 0x64400000 libsvn_delta-1-0.dll

Didn't know the rules about BaseAddress, just added another 200000 to 0x64200000 from previous post

**Comment by chucklu** [comment]
@albfan I got this error
 $ git svn rebase
C:\Program Files (x86)\Git\bin\perl.exe: *** unable to remap C:\Program Files (x
86)\Git\bin\libsvn_ra_svn-1-0.dll to same address as parent -- 0x6D510000
      0 [main] perl.exe" 6924 sync_with_child: child 7180(0x2D8) died before ini
tialization with status code 0x1
    985 [main] perl.exe" 6924 sync_with_child: *** child state child loading dll
s

**Comment by albfan** [comment]
@chucklu this should fix your problem

    > cd "C:\Program Files (x86)\Git\bin"
    > rebase -b 0x6D710000 libsvn_ra_svn-1-0.dll

**Comment by chucklu** [comment]
@albfan thank you very much
I have installed the cygwin ,and use ash.exe
/bin/rebaseall

**Comment by MerzDaniel** [comment]
@kblees , @albfan , @albfan 
I face multiple problems concerning git svn in Windows. From different posts throughout the internet I found many baseAddresses for the dlls. But nobody posts how they found out the specific 'baseaddress' for a '.dll'. My 'git svn' still doesn't work with all features for me. 

Where to get a full list of these base addresses? Try'n error seems not right for me...

**Comment by dscho** [comment]
@MerzDaniel you do know that you posted to an abandoned project, right? Did you try its successor, [Git for Windows 2.x](https://git-for-windows.github.io/) yet?

**Comment by MerzDaniel** [comment]
update to 2.x solved the problem :P

**Comment by chucklu** [comment]
@MerzDaniel  no, at least 1.x git svn can work
but in 2.x ,the git svn just crashed,you can find this issue
https://github.com/git-for-windows/git/issues/274

**Comment by MerzDaniel** [comment]
Then to be more accurate:
On my Windows7 x64
1) Deinstalling Git 1.9
2) Rebooting
3) Installing Git 2.9.2.windows.1
solved all my git svn related dll-Issues after all rebase memory address approaches failed to fix the problem for me.

**Pull request merged**
