### PR TITLE
Fix #232: Create .bash_profile if necessary

### PR DESCRIPTION
**Pull request by ArloL**

### CODE REVIEW

**Comment by dscho** [comment]
By the way, after `git commit --amend` with the suggested fixes (or even better), you can force push with `git push origin +HEAD` to update this PR; No need to open a new one.

Thanks!

**Comment by sschuberth** [comment]
Nit-pick: The commit message says "Fix #232", but that's a PR, not an issue, and it's already closed. So probably just omit this from the commit message.

**Comment by dscho** [comment]
@sschuberth points out that I completely missed the too short commit message. @ArloL let's replace it with some variation of this, okay?

```
Make sure that ~/.bashrc is not ignored

When users install a `~/.bashrc` they rightfully expect it to be 
executed as part of the regular Bash startup. However, this is not the 
case if it is not sourced explicitly from the `~/.bash_profile file.

This change installs such a `~/.bash_profile` unless there is already 
one.

Signed-off-by: ...
```

**Comment by ArloL** [comment]
I am not sure about the -a: http://stackoverflow.com/questions/321348/bash-if-a-vs-e-option

What do you think?

I will create a new PR with the commit message, if we agree on the line of code.

**Comment by dscho** [comment]
> I will create a new PR with the commit message, if we agree on the line of code.

Please don't. You can easily force-push a new version of your current branch. If you open new PRs every time you make an update to the commit, we really lose track.

**Comment by dscho** [comment]
> I am not sure about the -a: http://stackoverflow.com/questions/321348/bash-if-a-vs-e-option

I was talking about a different `-a`... From http://www.unix.com/man-page/Linux/1/test/:

```
EXPRESSION1 -a EXPRESSION2
	      both EXPRESSION1 and EXPRESSION2 are true
```

Note that this `-a` is put *after* the first expression and allows adding more expressions.

**Comment by dolmen** [comment]
`[[` is a bash built-in and should be used instead of `[`.

**Comment by dscho** [comment]
I *really* do not want to get into the habit of using Bashisms...

**Comment by dscho** [comment]
Thanks to @nalla, this has been finally addressed, in Git for Windows 2.x. Since Git for Windows 1.x was superseded by that new version, I am closing this here ticket.

**Pull request closed without merging**
