### PR TITLE
Set show-all-if-ambiguous to on

### PR DESCRIPTION
**Pull request by yuvale**
See issue https://github.com/msysgit/msysgit/issues/261.

### CODE REVIEW

**Comment by jkdufair** [comment]
I believe this setting should be left at the default value (off). It causes out-of-the-box behavior to be different in Git Bash than other out of the box behaviors in other environments (typical Linux distro installs, Mac OS, earlier versions of Git Bash)

**Comment by yuvale** [comment]
@jkdufair 
If maintaining user experience compatibility with vanilla *nix Bash is a goal of this project, then you're right. Same goes for other non-default settings in /etc/inputrc - `set completion-ignore-case on` and `set bell-style visible`, to name a few.
If however the goal is to provide a friendly Git environment for Windows users, then I'd say enabling `show-all-if-ambiguous` is a must.
Anyway, not my decision to make.

**Comment by dscho** [comment]
IMO the best user experience for Windows users really requires a GUI -- as [provided by GitHub](https://windows.github.com/). And the Microsoft developers also did a kick-ass job with the Git/GitHub integration of the Visual Studio.

The purpose of Git for Windows is to provide the same scriptable command-line interface enjoyed by developers whose development environment is on Linux and MacOSX. As such I would tend to agree with @jkdufair. Having said that, the best option would be to let the user choose at install time (and it would be best to default to Linux-like behavior).

Happily, it is [really easy to add a new page to the installer](https://github.com/git-for-windows/build-extra/commit/cbcf69b9aaa4d5a0ba90a3cd3c150b0418608b23). @jkdufair @yuvale why not giving it a try?

**Comment by jkdufair** [comment]
@dscho, Thank you for elucidating your reasoning. I believe it is
compelling and solid.

I don't prefer a page in the installer for the same reason I wouldn't want
a page in my Linux distro for selecting Bash options. The defaults are well
considered and altering my configuration post-install is simple.

**Comment by yuvale** [comment]
@dscho, note that all the features that are mentioned here are purely for interactive usage. They don't affect the scriptability aspect of the shell, if that's what worries you.

@jkdufair, changing your configuration post-install is simple *once you know what to look for*. It's nearly impossible for the typical Windows user who is just now using Bash for the first time.
At my workplace developers use Bash all the time (we're using OS X), still everyone thank me when I enable `completion-ignore-case` and `show-all-if-ambiguous` on their machines. Most people, including professional developers, just don't know that these things even exist.
So I think everyone's lives would be easier if at least some of these settings had different defaults.

Also, I don't agree that the defaults are well-considered. They're just older. :) Can anyone think of a compelling reason (aside from being the default on other systems) why these defaults are any good?

IMHO, give the users a decent user experience out of the box, and the few who care enough about what they're used to will find the way to get it back.

**Comment by jkdufair** [comment]
My argument for having turned off show-all-if-ambiguous off when it showed
up in a recent fit bash update is that the typical "tab complete the first
unambiguous part of a file name now causes a scroll. A few of those and the
git status I'm looking at for reference is now scrolled off the top of my
terminal window.

**Comment by yuvale** [comment]
@jkdufair You've raised a valid point, I agree.

On 4 במאי 2015, at 19:49, Jason Dufair <notifications@github.com> wrote:

My argument for having turned off show-all-if-ambiguous off when it showed
up in a recent fit bash update is that the typical "tab complete the first
unambiguous part of a file name now causes a scroll. A few of those and the
git status I'm looking at for reference is now scrolled off the top of my
terminal window.

On Monday, May 4, 2015, yuvale <notifications@github.com> wrote:

> @dscho <https://github.com/dscho>, note that all the features that are
> mentioned here are purely for interactive usage. They don't affect the
> scriptability aspect of the shell, if that's what worries you.
>
> @jkdufair <https://github.com/jkdufair>, changing your configuration
> post-install is simple *once you know what to look for*. It's nearly
> impossible for the typical Windows user who is just now using Bash for the
> first time.
> At my workplace developers use Bash all the time (we're using OS X), still
> everyone thank me when I enable completion-ignore-case and
> show-all-if-ambiguous on their machines. Most people, including
> professional developers, just don't know that these things even exist.
> So I think everyone's lives would be easier if at least some of these
> settings had different defaults.
>
> Also, I don't agree that the defaults are well-considered. They're just
> older. :) Can anyone think of a compelling reason (aside from being the
> default on other systems) why these defaults are any good?
>
> IMHO, give the users a decent user experience out of the box, and the few
> who care enough about what they're used to will find the way to get it
back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msysgit/msysgit/pull/262#issuecomment-98774703>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/msysgit/msysgit/pull/262#issuecomment-98776698>.

**Pull request merged**
