### PR TITLE
openssl: update to secure link

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by dscho** [comment]
Thank you for your contribution.

However, just switching to HTTPS does not make things safer, you would need to test a checksum, too. Happily, that is exactly how the MSys2 packages we are about to use in the upcoming Git for Windows release [does it](https://github.com/git-for-windows/MINGW-packages/blob/efc87a45304323d491090b3346d727109c2a67ad/mingw-w64-openssl/PKGBUILD#L17-L33).

Maybe you want to [have a look](https://github.com/git-for-windows/git/wiki/Building-Git)?

**Comment by vszakats** [comment]
The new project also uses non-HTTPS. Checksums are nice, but nevertheless it's good practice to use secure connections if they are available, also for the checksums themselves to be able to trust them.

**Comment by dscho** [comment]
> The new project also uses non-HTTPS. Checksums are nice

Actually, checksums are more reliable than HTTPS. Because you can be reasonably certain (at least if you use SHA-1 instead of MD5, and soon SHA-256 instead of SHA-1) that you are *really* talking about the *same* file as the original committer.

**Comment by dscho** [comment]
> You rejected a valid patch anyhow on the grounds that it doesn't solve a wider package management problem. I guess a typo fix wouldn't have qualified any better. And it didn't :(

Actually, I did not reject a valid patch. This patch mingled two unrelated things into a single commit. I just did not want to let you waste your time on something that is becoming obsolete as we speak...

I would be *delighted* to accept your contributions to the new Git for Windows.

**Comment by vszakats** [comment]
Checksums are useful only if you received them _unaltered_ from an _authentic source_. HTTPS highly raises the chances of achieving these. On the other hand when using plain HTTP, the checksum cannot be trusted at all (it can be altered by a MITM). Of course, I can't tell where you pull your checksums from, but if you happen to use plaintext (HTTP) to download the sources, there is a chance you use plaintext to acquire the checksums too, making the whole process pointless. If you generate the checksums yourself from a tarball downloaded from a plaintext URL, it is pointless as well.

My point is, using HTTPS costs nothing, and enabling it on downloads at best will help resolving above issues, and in worst case won't cause any problem at all, therefore it's good practice to use it, if available.

**Comment by dscho** [comment]
> Checksums are useful only if you received them unaltered from an authentic source.

Right. In our case, the source is the Git repository. If you distrust the checksum, you *must* distrust the URL (HTTPS or not) because it comes from the very same source as the URL.

**Comment by vszakats** [comment]
I meant the original source where the checksum came from, f.e. the openssl.org homepage. Or the original source package from openssl.org page if you generated the checksum yourself after downloading it. If you used any HTTP protocol in any of these steps, your checksum is just decoration. However if you used HTTPS to download from openssl.org and/or to load the page showing the original checksum, chances are good they _can_ be trusted. The source I tried to patch here uses HTTP, which may or may not indicate that the chain of trust was broken somewhere, but is certainly not a good sign.

What I see is that HTTP is preferred in this project for an unknown reason.

**Comment by dscho** [comment]
> What I see is that HTTP is preferred in this project for an unknown reason.

Wrong impression. The correct impression would be: with a better commit message (and with two separate commits for the two unrelated changes), the PR would even have been accepted. But I closed it because I wanted to save both you and myself time in favor of working on the *new* Git SDK instead.

I see that I failed, we both spent considerable time beating with sticks on this dead horse.

**Comment by vszakats** [comment]
Okay, so the commit message is wrong. Or, that a totally humble but also valid typo is also fixed at the same time. Whichever the case is, it's probably best to discuss _before_ rejecting a PR. What I see is that we're circling around formalities instead of fixing the damn thing with a single 'Merge PR' click.

**Comment by dscho** [comment]
I understand that you find the use of the HTTP protocol sloppy and unacceptable when HTTPS is available. Likewise, please understand that I as a fix for such a sloppiness to abide by certain, not even high standards: commit messages should be clear, provide information that cannot easily be deduced from the diff but is necessary to understand the what/why/when/how/where/who of the commit, and they certainly should not contain misleading information (it is known that certificates can now be forged even by parties with common funding, so to suggest that HTTPS just makes things safe is only giving a false sense of security), commits need to be properly separated by concern.

If it was indeed only a bug fix, I would probably have overlooked the shortcomings of the patch.

But what you want to do is make our project more diligent, and you can only do that by making diligent commits and pull requests.

Now, we have overspent the time I wanted to give this minor issue in a project that I am working hard to supersede with [a better one](https://github.com/git-for-windows). I guess I might just as well have the benefit of a well crafted Pull Request that simply fixes the shortcomings I point out instead of reacting with snide remarks. But I see that despite continuing to spend my time, you already deleted your fork and obviously have no intention of fixing your Pull Request? If that is the case, let's let this PR rest in peace.

**Comment by vszakats** [comment]
Well, you started with the "sneaky" remark (after closing the PR), which I wish you to be the sneakiest and most ill-intended patch to ever happen to this project. And now you lecture about diligence. I'll leave you the exercise to create a separate 1 character patch and "sneaky" 4 character case update patch, it just simply doesn't make any sense to me, not even in the name of diligence, sorry.

**Pull request closed without merging**
